
package business;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddOrderHandlerService", targetNamespace = "http://business/", wsdlLocation = "http://localhost:8080/domain-model-ee-business/AddOrderHandler?wsdl")
public class AddOrderHandlerService
    extends Service
{

    private final static URL ADDORDERHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDORDERHANDLERSERVICE_EXCEPTION;
    private final static QName ADDORDERHANDLERSERVICE_QNAME = new QName("http://business/", "AddOrderHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/domain-model-ee-business/AddOrderHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDORDERHANDLERSERVICE_WSDL_LOCATION = url;
        ADDORDERHANDLERSERVICE_EXCEPTION = e;
    }

    public AddOrderHandlerService() {
        super(__getWsdlLocation(), ADDORDERHANDLERSERVICE_QNAME);
    }

    public AddOrderHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDORDERHANDLERSERVICE_QNAME, features);
    }

    public AddOrderHandlerService(URL wsdlLocation) {
        super(wsdlLocation, ADDORDERHANDLERSERVICE_QNAME);
    }

    public AddOrderHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDORDERHANDLERSERVICE_QNAME, features);
    }

    public AddOrderHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddOrderHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddOrderHandler
     */
    @WebEndpoint(name = "AddOrderHandlerPort")
    public AddOrderHandler getAddOrderHandlerPort() {
        return super.getPort(new QName("http://business/", "AddOrderHandlerPort"), AddOrderHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddOrderHandler
     */
    @WebEndpoint(name = "AddOrderHandlerPort")
    public AddOrderHandler getAddOrderHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business/", "AddOrderHandlerPort"), AddOrderHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDORDERHANDLERSERVICE_EXCEPTION!= null) {
            throw ADDORDERHANDLERSERVICE_EXCEPTION;
        }
        return ADDORDERHANDLERSERVICE_WSDL_LOCATION;
    }

}
