
package business;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddOrderHandler", targetNamespace = "http://business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddOrderHandler {


    /**
     * 
     * @param arg0
     * @return
     *     returns business.ProductDTO
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "productDetails", targetNamespace = "http://business/", className = "business.ProductDetails")
    @ResponseWrapper(localName = "productDetailsResponse", targetNamespace = "http://business/", className = "business.ProductDetailsResponse")
    public ProductDTO productDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ApplicationException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns business.SupplierDTO
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareOrder", targetNamespace = "http://business/", className = "business.PrepareOrder")
    @ResponseWrapper(localName = "prepareOrderResponse", targetNamespace = "http://business/", className = "business.PrepareOrderResponse")
    public SupplierDTO prepareOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ApplicationException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns business.OrdersDTO
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://business/", className = "business.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://business/", className = "business.AddOrderResponse")
    public OrdersDTO addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3)
        throws ApplicationException_Exception
    ;

}
