
package business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetOrdersHandler", targetNamespace = "http://business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetOrdersHandler {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<business.OrdersDTO>
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrdersByProduct", targetNamespace = "http://business/", className = "business.GetOrdersByProduct")
    @ResponseWrapper(localName = "getOrdersByProductResponse", targetNamespace = "http://business/", className = "business.GetOrdersByProductResponse")
    public List<OrdersDTO> getOrdersByProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ApplicationException_Exception
    ;

}
