
package business;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetOrdersHandlerService", targetNamespace = "http://business/", wsdlLocation = "http://localhost:8080/domain-model-ee-business/GetOrdersHandler?wsdl")
public class GetOrdersHandlerService
    extends Service
{

    private final static URL GETORDERSHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETORDERSHANDLERSERVICE_EXCEPTION;
    private final static QName GETORDERSHANDLERSERVICE_QNAME = new QName("http://business/", "GetOrdersHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/domain-model-ee-business/GetOrdersHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETORDERSHANDLERSERVICE_WSDL_LOCATION = url;
        GETORDERSHANDLERSERVICE_EXCEPTION = e;
    }

    public GetOrdersHandlerService() {
        super(__getWsdlLocation(), GETORDERSHANDLERSERVICE_QNAME);
    }

    public GetOrdersHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETORDERSHANDLERSERVICE_QNAME, features);
    }

    public GetOrdersHandlerService(URL wsdlLocation) {
        super(wsdlLocation, GETORDERSHANDLERSERVICE_QNAME);
    }

    public GetOrdersHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETORDERSHANDLERSERVICE_QNAME, features);
    }

    public GetOrdersHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOrdersHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetOrdersHandler
     */
    @WebEndpoint(name = "GetOrdersHandlerPort")
    public GetOrdersHandler getGetOrdersHandlerPort() {
        return super.getPort(new QName("http://business/", "GetOrdersHandlerPort"), GetOrdersHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOrdersHandler
     */
    @WebEndpoint(name = "GetOrdersHandlerPort")
    public GetOrdersHandler getGetOrdersHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business/", "GetOrdersHandlerPort"), GetOrdersHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETORDERSHANDLERSERVICE_EXCEPTION!= null) {
            throw GETORDERSHANDLERSERVICE_EXCEPTION;
        }
        return GETORDERSHANDLERSERVICE_WSDL_LOCATION;
    }

}
