
package business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiveOrderHandler", targetNamespace = "http://business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveOrderHandler {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "receiveOrder", targetNamespace = "http://business/", className = "business.ReceiveOrder")
    @ResponseWrapper(localName = "receiveOrderResponse", targetNamespace = "http://business/", className = "business.ReceiveOrderResponse")
    public void receiveOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws ApplicationException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<business.OrdersDTO>
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrdersBySupplier", targetNamespace = "http://business/", className = "business.GetOrdersBySupplier")
    @ResponseWrapper(localName = "getOrdersBySupplierResponse", targetNamespace = "http://business/", className = "business.GetOrdersBySupplierResponse")
    public List<OrdersDTO> getOrdersBySupplier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ApplicationException_Exception
    ;

}
